class Node:
    name: str
    attrs: dict[str, str]
    children: list[Node]
    text: str

    def __to_string(self, spacing: int | None) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

def read_file(file_path: str, root_tag: str) -> Node: ...
def read_string(xml_string: str, root_tag: str) -> Node: ...
